---
version: "3"

networks:  
  net1:
    enable_ipv6: false
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.1.0/24
        gateway: 192.168.1.1
  net100:
    enable_ipv6: false
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.100.0/24
        gateway: 192.168.100.1
  net200:
    enable_ipv6: false
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.200.0/24
        gateway: 192.168.200.1
services: 
  router100:
    image: frrouting/frr:v8.4.0
    volumes:
      - ./router100/staticd.conf:/etc/frr/staticd.conf
    networks:
      net1:
        ipv4_address: 192.168.1.100
      net100:
        ipv4_address: 192.168.100.100
    cap_add:
      - CAP_NET_RAW
      - NET_ADMIN
      - SYS_ADMIN
  router200:
    image: frrouting/frr:v8.4.0
    volumes:
      - ./router200/staticd.conf:/etc/frr/staticd.conf
    networks:
      net1:
        ipv4_address: 192.168.1.200
      net200:
        ipv4_address: 192.168.200.200
    cap_add:
      - CAP_NET_RAW
      - NET_ADMIN
      - SYS_ADMIN

