version: "3.7"
services:
  apache:
    image: bhawiyuga/pentesting:2.4.49-alpine
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "80:8080"
  attacker:
    image: kalilinux/custom-kali
    build:
      context: .
      dockerfile: Dockerfile.kali
    command: sleep infinity
